src/Entity/Carsharing.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarsharingRepository")
 */
class Carsharing
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\StageApi", inversedBy="carsharings")
     */
    private $stage_api;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="driver_carsharings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $driver;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="passenger_carsharings")
     */
    private $passengers;

    /**
     * @ORM\Column(type="time")
     */
    private $appointment_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $appointment_to;

    /**
     * @ORM\Column(type="integer")
     */
    private $seat_number;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function __construct()
    {
        $this->passengers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStageApi(): ?StageApi
    {
        return $this->stage_api;
    }

    public function setStageApi(?StageApi $stage_api): self
    {
        $this->stage_api = $stage_api;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->driver;
    }

    public function setDriver(?User $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getPassengers(): Collection
    {
        return $this->passengers;
    }

    public function addPassenger(User $passenger): self
    {
        if (!$this->passengers->contains($passenger)) {
            $this->passengers[] = $passenger;
        }

        return $this;
    }

    public function removePassenger(User $passenger): self
    {
        if ($this->passengers->contains($passenger)) {
            $this->passengers->removeElement($passenger);
        }

        return $this;
    }

    public function getAppointmentAt(): ?\DateTimeInterface
    {
        return $this->appointment_at;
    }

    public function setAppointmentAt(\DateTimeInterface $appointment_at): self
    {
        $this->appointment_at = $appointment_at;

        return $this;
    }

    public function getAppointmentTo(): ?string
    {
        return $this->appointment_to;
    }

    public function setAppointmentTo(string $appointment_to): self
    {
        $this->appointment_to = $appointment_to;

        return $this;
    }

    public function getSeatNumber(): ?int
    {
        return $this->seat_number;
    }

    public function setSeatNumber(int $seat_number): self
    {
        $this->seat_number = $seat_number;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function __toString(){
        return 'covoiturage pour le ' . $this->stage_api;
    }
}

src/Form/CarsharingType.php
<?php

namespace App\Form;

use App\Entity\StageApi;
use App\Entity\Carsharing;
use Doctrine\ORM\EntityRepository;
use App\Repository\StageApiRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type as Type;

class CarsharingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('stage_api', EntityType::class, [
                'class' => StageApi::class,
                'label' => 'Stage',
                'label_attr' => [
                    'class' => 'text-primary'
                ],
            ])
            ->add('seat_number', Type\IntegerType::class, [
                'label' => 'Nombre de place',
                'label_attr' => [
                    'class' => 'text-primary'
                ],
                'attr' => [
                    'min' => 1
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'Vous devez spécifier un nombre de place'
                    ]),
                    new Range([
                        'min' => 1,
                        'minMessage' => 'Vous devez proposer au minimum 1 place'
                    ])
                ]
            ])
            ->add('appointment_at', Type\TimeType::class, [
                'label' => 'Heure de rendez-vous',
                'label_attr' => [
                    'class' => 'text-primary'
                ],
                'widget' => 'single_text',
                'empty_data' => 'un string',
                'attr' => ['class' => 'timepicker'],
                'constraints' => [
                    new Assert\Time(),
                ]
            ])
            ->add('appointment_to', Type\TextType::class, [
                'label' => 'Lieu de rendez-vous',
                'label_attr' => [
                    'class' => 'text-primary'
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'Vous devez spécifier un lieu de rendez-vous'
                    ]),
                    new Assert\Length([
                        'minMessage' => 'Le lieu de rendez-vous est trop court, {{ limit }} caractère minimunm',
                        'min' => 5
                    ])
                ]
            ])
            ->add('comment', Type\TextareaType::class,[
                'label' => 'Ajouter un commentaire (facultatif)',
                'label_attr' => [
                    'class' => 'text-primary'
                ],
                'attr' => ['rows' => '2'],
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Carsharing::class,
        ]);
    }
}

src/Controller/CarsharingController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;

use App\Entity\User;
use App\Entity\Carsharing;
use App\Repository\CarsharingRepository;
use App\Form\CarsharingType;

/**
 * @Route("/membre/covoiturage", name="carsharing_")
 */
class CarsharingController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(CarsharingRepository $carsharingRepo)
    {
        $user = $this->getUser();

        $carsharings = $carsharingRepo->findAllExceptDriverEqualUser($user);

        foreach ($carsharings as $key => $carsharing) {

            // on l'enlève du tableau carsharings le carsharing pour lequel l'user est deja passager
            if ($carsharing->getPassengers()->contains($user)) {
                unset($carsharings[$key]);
            }

            // on enlève du tableau carsharings le carsharing qui n'ont plus de place disponible
            if ($carsharing->getPassengers()->count() >= $carsharing->getSeatNumber()) {
                unset($carsharings[$key]);
            }
        }
        
        return $this->render('carsharing/index.html.twig', [
            'carsharings' => $carsharings,
        ]);
    }

    /**
     * @Route("/ajout", name="new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $em)
    {
        $carsharing = new Carsharing();

        $form = $this->createForm(CarsharingType::class, $carsharing);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user = $this->getUser();

            $carsharing->setDriver($user);

            $em->persist($carsharing);
            $em->flush();
            $this->addFlash('success', 'Le co-voiturage a bien été enregistré');

            return $this->redirectToRoute('user_dashboard');
        }

        return $this->render('carsharing/new.html.twig', [
            'carsharing' => $carsharing,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/prendre/{id}", name="take", methods={"GET"})
     */
    public function take(Carsharing $carsharing, EntityManagerInterface $em)
    {
        $user = $this->getUser();

        // On ajoute l'user comme passager uiquement si il reste des place disponible
        if ( $carsharing->getPassengers()->count() < $carsharing->getSeatNumber() ) {

            $carsharing->addPassenger($user);

            $em->persist($carsharing);
            $em->flush();

            $this->addFlash('success', 'Félicitation ! Vous voila inscrit au co-voiturage pour le stage de ' . $carsharing->getStageApi()->getAnimator());

            return $this->redirectToRoute('user_dashboard');
        }

        $this->addFlash('danger', 'Ce co-voiturage n\'est plus disponible');

        return $this->redirectToRoute('carsharing_index');
    }

    /**
     * @Route("/tous-les-covoiturages", name="show-all", methods={"GET"})
     */
    public function showAll(CarsharingRepository $carsharingRepo)
    {
        $carsharings = $carsharingRepo->findAll();

        return $this->render('carsharing/show-all.html.twig', [
            'carsharings' => $carsharings
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Carsharing $carsharing)
    {
        return $this->render('carsharing/show.html.twig', [
            'carsharing' => $carsharing
        ]);
    }

    

    /**
     * @Route("/modification", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request)
    {

    }

    /**
     * @Route("/suppression/{id}", name="delete", methods={"GET","DELETE"})
     */
    public function delete(Carsharing $carsharing, EntityManagerInterface $em, Request $request)
    {
        $page = $request->get("page");

        $em->remove($carsharing);
        $em->flush();

        $this->addFlash('success', 'le co-voiturage à bien été supprimé');

        if ($page == "admin") {
            return $this->redirectToRoute('carsharing_show-all');
        } elseif ($page == "profil") {
            return $this->redirectToRoute('user_dashboard');
        }
    }

    /**
     * @Route("/suppression/{id}/place", name="remove-place", methods={"GET","DELETE"})
     */
    public function removePlace(Carsharing $carsharing, EntityManagerInterface $em, Request $request)
    {
        $user = $this->getUser();
        $user->removePassengerCarsharing($carsharing);

        $em->persist($user);
        $em->flush();

        $this->addFlash('success', 'Vous n\'êtes plus inscrit sur le co-voiturage pour le ' . $carsharing->getStageApi());

        return $this->redirectToRoute('user_dashboard');
    }
}

templates/carsharing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Co-voiturage{% endblock %}

{% block page %}
<div class="carsharing-section justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto mb-5 text-center">
                {# Titre de la page #}
                <h1 class="mx-auto mb-5 text-uppercase">Co-voiturage</h1>
                <h3 class="text-primary mb-5">Vous voulez vous rendre à un stage ?</h3>
                <h5 class="text-white">Rejoignez un Co-voiturage en cliquant dans la liste ou proposez en un !</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto text-center mb-5 black-list">
                <div class="list-group scrollable-200">
                {% for carsharing in carsharings %}
                    <a href="{{ path('carsharing_take', { "id": carsharing.id }) }}" class="list-group-item list-group-item-action text-white">
                        {{ carsharing.stageApi.date }} pour le stage de <span class="font-weight-bold text-primary">{{ carsharing.stageApi.animator }}</span> : Départ à {{ carsharing.appointmentAt|date('H:i') }}
                    </a>
                {% else %}
                    <div class="list-group text-white">Il y a aucun Co-voiturage de disponible, Créer en un !</div>
                {% endfor %}
                </div>
            </div>
            <div class="col-lg-8 mx-auto text-center">
                <a href="{{ path('carsharing_new') }}" class="btn btn-primary">Proposer un Co-voiturage</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block modal %}

<!-- Inclusion du modal de confirmation d'inscription à un co-voiturage -->
{% include "_partials/_modal.html.twig" %}

{% endblock %}

templates/carsharing/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout covoiturage{% endblock %}

{% block page %}
<div class="carsharing-section justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto mb-5 text-center">
            
                <h1 class="mx-auto mb-5 text-uppercase">Co-voiturage</h1>
                <h2 class="text-primary mb-5">Proposer un co-voiturage</h2>
                
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                
                {{ form_widget(form) }}
                
                <button class="btn btn-primary mt-5">{{ button_label|default('Enregistrer') }}</button>
                
                {{ form_end(form) }}
                
                <div class="mt-5">
                    <a href="{{ path('carsharing_index') }}">Retour</a>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/carsharing/show-all.html.twig
{% extends 'base.html.twig' %}

{% block title %}tous les covoiturages{% endblock %}

{% block page %}

<div class="admin-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto mb-5 text-center">
                {# Titre de la page #}
                <h1 class="mx-auto mb-5 text-uppercase">Administration</h1>
                <h2 class="text-white">Liste des Co-voiturage</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 mx-auto mb-5 text-center">
                <div class="col-lg-6 mx-auto">
                    <div class="form-group">
                        <label for="search_box" class="text-white">Stage / Conducteur / Passagers / Heure / Lieux / Commentaire</label>
                        <input id="search_box" class="form-control" type="text" placeholder="Rechercher...">
                    </div>
                </div>

                <div class="table-responsive text-white">
                    <table id="scrollTable" class="text-white">
                        <thead>
                            <tr>
                                <th>Stage</th>
                                <th>Conducteur</th>
                                <th>Passagers</th>
                                <th>Sièges</th>
                                <th>Heure</th>
                                <th>Lieux</th>
                                <th>Commentaire</th>
                                <th>Supprimer</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for carsharing in carsharings %}
                            <tr>
                                <td>{{ carsharing.stageApi.animator }} <br> {{ carsharing.stageApi.date }}</td>
                                <td>{{ carsharing.driver }}</td>
                                <td>
                                    {% for passenger in carsharing.passengers %}
                                        <p class="m-0 text-nowrap">{{ loop.index }}-{{ passenger }}</p>
                                    {% else %}
                                        <p class="m-0">Aucun</p>
                                    {% endfor %}
                                </td>
                                <td>{{ carsharing.seatNumber }}</td>
                                <td>{{ carsharing.appointmentAt|date('H:i') }}</td>
                                <td>{{ carsharing.appointmentTo }}</td>
                                <td>{{ carsharing.comment ? carsharing.comment : 'Aucun' }}</td>

                                <td>
                                {# la class "confirmDelete" fait référence à du js qui appelle ensuite le modal coorrespondant situé dans le fichier inclus en fin de page #}
                                    <a class="confirmDeleteCarsharing" href="{{ path('carsharing_delete', {"id" : carsharing.id, "page" : "admin"}) }}" >
                                        <i class="fas fa-user-times fa-2x text-danger"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="mt-5">
                    <a href="{{ path('carsharing_index') }}">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block modal %}

<!-- Inclusion du modal de confirmation de suppression -->
{% include "_partials/_modal.html.twig" %}

{% endblock %}

templates/carsharing/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}covoiturage{% endblock %}

{% block page %}

{{ dump(carsharing) }}

{% endblock %}