src/Entity/Carsharing.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarsharingRepository")
 */
class Carsharing
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\StageApi", inversedBy="carsharings")
     */
    private $stage_api;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="driver_carsharings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $driver;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="passenger_carsharings")
     */
    private $passengers;

    /**
     * @ORM\Column(type="time")
     */
    private $appointment_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $appointment_to;

    /**
     * @ORM\Column(type="integer")
     */
    private $seat_number;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function __construct()
    {
        $this->passengers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStageApi(): ?StageApi
    {
        return $this->stage_api;
    }

    public function setStageApi(?StageApi $stage_api): self
    {
        $this->stage_api = $stage_api;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->driver;
    }

    public function setDriver(?User $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getPassengers(): Collection
    {
        return $this->passengers;
    }

    public function addPassenger(User $passenger): self
    {
        if (!$this->passengers->contains($passenger)) {
            $this->passengers[] = $passenger;
        }

        return $this;
    }

    public function removePassenger(User $passenger): self
    {
        if ($this->passengers->contains($passenger)) {
            $this->passengers->removeElement($passenger);
        }

        return $this;
    }

    public function getAppointmentAt(): ?\DateTimeInterface
    {
        return $this->appointment_at;
    }

    public function setAppointmentAt(\DateTimeInterface $appointment_at): self
    {
        $this->appointment_at = $appointment_at;

        return $this;
    }

    public function getAppointmentTo(): ?string
    {
        return $this->appointment_to;
    }

    public function setAppointmentTo(string $appointment_to): self
    {
        $this->appointment_to = $appointment_to;

        return $this;
    }

    public function getSeatNumber(): ?int
    {
        return $this->seat_number;
    }

    public function setSeatNumber(int $seat_number): self
    {
        $this->seat_number = $seat_number;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function __toString(){
        return 'covoiturage pour le ' . $this->stage_api;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity; # permet que l'utilisateur créé en BDD soit unique et donc n'existe pas déjà (annotation : unique=true à ajouter sur les propriétés concernées)

/**
 * @ORM\Table(name="app_users")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields="name", message="Ce nom utilisateur est déjà pris")
 * @UniqueEntity(fields="email", message="Cet email est déjà pris")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $firstname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $license;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $responsability;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Role", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $role;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Grade", inversedBy="users")
     */
    private $grades;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Technique", inversedBy="users")
     */
    private $technics;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $teacher_comment;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Carsharing", mappedBy="passengers")
     */
    private $passenger_carsharings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Carsharing", mappedBy="driver", cascade={"persist", "remove"})
     */
    private $driver_carsharings;

    public function __construct()
    {
        $this->grades = new ArrayCollection();
        $this->technics = new ArrayCollection();
        $this->carsharings = new ArrayCollection();
        $this->driver_carsharings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getLicense(): ?string
    {
        return $this->license;
    }

    public function setLicense(?string $license): self
    {
        $this->license = $license;

        return $this;
    }

    public function getResponsability(): ?string
    {
        return $this->responsability;
    }

    public function setResponsability(string $responsability): self
    {
        $this->responsability = $responsability;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return Collection|Grade[]
     */
    public function getGrades(): Collection
    {
        return $this->grades;
    }

    public function setGrades()
    {
        $this->grades = $grade;

        return $this;
    }

    public function addGrade(Grade $grade): self
    {
        if (!$this->grades->contains($grade)) {
            $this->grades[] = $grade;
        }

        return $this;
    }

    public function removeGrade(Grade $grade): self
    {
        if ($this->grades->contains($grade)) {
            $this->grades->removeElement($grade);
        }

        return $this;
    }

    /**
     * @return Collection|Technique[]
     */
    public function getTechnics(): Collection
    {
        return $this->technics;
    }

    public function addTechnic(Technique $technic): self
    {
        if (!$this->technics->contains($technic)) {
            $this->technics[] = $technic;
        }

        return $this;
    }

    public function removeTechnic(Technique $technic): self
    {
        if ($this->technics->contains($technic)) {
            $this->technics->removeElement($technic);
        }

        return $this;
    }

    public function getTeacherComment(): ?string
    {
        return $this->teacher_comment;
    }

    public function setTeacherComment(?string $teacher_comment): self
    {
        $this->teacher_comment = $teacher_comment;

        return $this;
    }

    // Ajouté pour le bon fonctionnement de l'encodage à l'aide de UserPasswordEncoderInterface
    public function getSalt()
    {
        return null;
    }

    public function getRoles(){
        return [$this->getRole()->getCode()];
    }

    public function getUsername(){
        return $this->name;
    }

    public function eraseCredentials(){
    }

    /**
     * @return Collection|Carsharing[]
     */
    public function getPassengerCarsharings(): Collection
    {
        return $this->passenger_carsharings;
    }

    public function addPassengerCarsharing(Carsharing $passengerCarsharing): self
    {
        if (!$this->passenger_carsharings->contains($passengerCarsharing)) {
            $this->passenger_carsharings[] = $passengerCarsharing;
            $passengerCarsharing->addPassenger($this);
        }

        return $this;
    }

    public function removePassengerCarsharing(Carsharing $passengerCarsharing): self
    {
        if ($this->passenger_carsharings->contains($passengerCarsharing)) {
            $this->passenger_carsharings->removeElement($passengerCarsharing);
            $passengerCarsharing->removePassenger($this);
        }

        return $this;
    }

    /**
     * @return Collection|Carsharing[]
     */
    public function getDriverCarsharings(): Collection
    {
        return $this->driver_carsharings;
    }

    public function addDriverCarsharing(Carsharing $driverCarsharing): self
    {
        if (!$this->driver_carsharings->contains($driverCarsharing)) {
            $this->driver_carsharings[] = $driverCarsharing;
            $driverCarsharing->setDriver($this);
        }

        return $this;
    }

    public function removeDriverCarsharing(Carsharing $driverCarsharing): self
    {
        if ($this->driver_carsharings->contains($driverCarsharing)) {
            $this->driver_carsharings->removeElement($driverCarsharing);
            // set the owning side to null (unless already changed)
            if ($driverCarsharing->getDriver() === $this) {
                $driverCarsharing->setDriver(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\UserEditType;
use App\Form\UserPasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/membre/profil", name="user_")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="dashboard")
     */
    public function index()
    {
        $user = $this->getUser();

        return $this->render('user/index.html.twig', [
            'user' => $user
        ]);
    }

    /**
     * @Route("/modification", name="edit")
     */
    public function edit(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
            $this->addFlash('success', 'Profil modifié.');
            return $this->redirectToRoute('user_dashboard');
        }
        return $this->render('user/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/modification/motdepasse", name="edit_password")
     */
    public function editPassword(Request $request, UserPasswordEncoderInterface $encoder)
    {
        $user = $this->getUser();
        $form = $this->createForm(UserPasswordType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
                $encoder->encodePassword(
                    $user,
                    $form->get('newPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
            $this->addFlash('success', 'Mot de passe modifié.');
            return $this->redirectToRoute('user_dashboard');
        }
        return $this->render('user/edit_password.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de mes informations{% endblock %}

{% block page %}

<div class="user-section justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
            
                <h1 class="mx-auto mb-5 text-uppercase">Mon compte</h1>
                <h2 class="text-primary mb-5">Modifier mes informations</h2>
                
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                
                {{ form_widget(form) }}
                
                <button class="btn btn-primary mt-5">{{ button_label|default('Enregistrer') }}</button>
                
                {{ form_end(form) }}
                
                <div class="mt-5">
                    <a href="{{ path('user_dashboard') }}">Retour</a>
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/edit_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition du mot de passe{% endblock %}

{% block page %}

<div class="user-section justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
            
                <h1 class="mx-auto mb-5 text-uppercase">Mon compte</h1>
                <h2 class="text-primary mb-5">Changer mon mot de passe</h2>
                
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                
                {{ form_widget(form) }}
                
                <button class="btn btn-primary mt-5">{{ button_label|default('Enregistrer') }}</button>
                
                {{ form_end(form) }}
                
                <div class="mt-5">
                    <a href="{{ path('user_dashboard') }}">Retour</a>
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block page %}

<section class="user-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="mx-auto my-0 text-uppercase mb-5">Mon compte</h1>
                <h2 class="text-primary mb-5">Dashboard</h2>
            </div>

            <div class="col-lg-6">
                <h3 class="text-white mb-5 text-center">Informations personnelles</h3>

                <div class="list-group mb-5 scrollable-400 black-list text-center">
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Nom : </span>{{ user.name }}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Prénom : </span>{{ user.firstname }}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Date de naissance : </span>{{ user.birthdate |date("m/d/Y")}}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Adresse : </span>{{ user.address }}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Adresse e-mail : </span>{{ user.email }}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Numéro de téléphone : </span>{{ user.phone }}</p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0"><span class="text-primary">Numéro de licence : </span>{{ user.license }}</p>
                    </div>
                </div>

                {% if app.user.id == user.id %}                     
                    <div class="row mb-4">
                        <div class="col-lg-6">
                            <a href="{{ path('user_edit') }}" class="btn btn-block btn-primary">Modifier mon profil</a>
                        </div>
                        <div class="col-lg-6">
                            <a href="{{ path('user_edit_password') }}" class="btn btn-block btn-primary">Modifier mon mot de passe</a>
                        </div>                      
                    </div>
                {% endif %}
            </div>

            <div class="col-lg-6">
                <h3 class="text-white mb-5 text-center">Niveau technique</h3>
                
                <div class="list-group mb-5 scrollable-400 black-list text-center">
                    <div class="list-group-item">
                        <p class="m-0">
                        <span class="text-primary">Mon grade : </span>
                        {% for grade in user.grades %}
                            {{ grade.name }}
                        {% endfor %}
                        </p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0">
                        <span class="text-primary">Technique(s) à travailler : </span>
                            <div class="row d-flex flex-row justify-content-center mt-2 mb-n3">
                                {% for technic in user.technics %}
                                    <div class="col-sm-2 badge badge-primary m-2 p-2">{{ technic.attack }}<br>{{ technic.title }}<br>{{ technic.side }}</div>
                                {% endfor %}
                            </div>
                        </p>
                    </div>
                    <div class="list-group-item">
                        <p class="m-0">
                        <span class="text-primary">Commentaire d'un professeur : </span>{{ user.teacherComment }}
                        </p>
                    </div>
                </div>
            </div>

            <div class="row w-100 mt-5">
                <div class="col-lg-12">
                    <h3 class="text-white mb-5 text-center">Co-voiturage</h3>
                </div>
                <div class="col-lg-6">
                    <h4 class="text-white mb-5 text-center text-primary">Conducteur</h4>
                    
                    <div class="list-group mb-5 scrollable-400 black-list text-center">
                        {% for carsharing in user.driverCarsharings %}
                            <div class="list-group-item">
                                <p class="m-0">
                                    <span class="text-primary">Départ: </span>
                                    {{ carsharing.stageApi.date }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">À : </span>
                                    {{ carsharing.appointmentAt|date('h:i') }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Stage : </span>
                                    {{ carsharing.stageApi.animator }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Passagers : </span>
                                    {% for passager in carsharing.passengers %}
                                        {{ passager }}{% if loop != loop.last %}, {% endif %}

                                    {% else %}
                                        Aucun
                                    {% endfor %}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Places disponible : </span>
                                    {% if carsharing.passengers|length == carsharing.seatNumber %}
                                        Complet
                                    {% else %}
                                        {{ carsharing.seatNumber - carsharing.passengers|length }}
                                    {% endif %}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Total places : </span>
                                    {{ carsharing.seatNumber }}
                                </p>
                                <p class="m-0">
                                    <a class="confirmDeleteCarsharing" href="{{ path('carsharing_delete', {"id" : carsharing.id, "page" : "profil"}) }}" >
                                        <span class="text-danger">Supprimer le co-voiturage</span>
                                    </a>
                                </p>
                            </div>
                        {% else %}
                            <div class="">
                                <p class="m-0">
                                <span class="text-white">Pas de co-voiturage de prevu</span>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <h4 class="text-white mb-5 text-center text-primary">Passager</h4>
                    
                    <div class="list-group mb-5 scrollable-400 black-list text-center">
                        {% for carsharing in user.passengerCarsharings %}
                            <div class="list-group-item">
                                <p class="m-0">
                                    <span class="text-primary">Départ: </span>
                                    {{ carsharing.stageApi.date }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">À : </span>
                                    {{ carsharing.appointmentAt|date('h:i') }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Stage : </span>
                                    {{ carsharing.stageApi.animator }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Conducteur : </span>
                                    {{ carsharing.driver }}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Passagers : </span>
                                    {% for passager in carsharing.passengers %}
                                        {{ passager }}{% if loop != loop.last %}, {% endif %}

                                    {% else %}
                                        Aucun
                                    {% endfor %}
                                </p>
                                <p class="m-0">
                                    <span class="text-primary">Places disponible : </span>
                                    {% if carsharing.passengers|length == carsharing.seatNumber %}
                                        Complet
                                    {% else %}
                                        {{ carsharing.seatNumber - carsharing.passengers|length }}
                                    {% endif %}
                                </p>
                                <p class="m-0">
                                    <a class="confirmUnjoinCarsharing" href="{{ path('carsharing_remove-place', {"id" : carsharing.id}) }}" >
                                        <span class="text-warning">Se désinscrire</span>
                                    </a>
                                </p>
                            </div>
                        {% else %}
                            <div class="">
                                <p class="m-0">
                                <span class="text-white">Pas de co-voiturage de prevu</span>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock %}

{% block modal %}

<!-- Inclusion du modal de confirmation de suppression -->
{% include "_partials/_modal.html.twig" %}

{% endblock %}